out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: BPIC15M4
dataset:
  format: PyG-EVENTBPIC15M4
  name: BPIC15M4cycletimeprediction
  task: graph
  task_type: regression
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: TypeDictNode+LapPE+RWSE
  node_encoder_num_types: 354
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TwoLayerLinearEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 1
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,16)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: GINE+Transformer
  layers: 5
  n_heads: 8
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph # can be san_graph or default
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean  
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 100
